image: registry.vela/velaluqa/gitlab-ci-build-images:ruby-2.3.4-docker-compose

variables:
  BUNDLE_GEMFILE: Gemfile-ci
  REGISTRY: registry.velalu.qa
  COMPOSE_FILE: docker-compose-ci.yml
  COMPOSE_PROJECT_NAME: $CI_PIPELINE_ID

cache:
  key: 'ruby234'
  paths:
    - vendor/bundle

before_script:
  - bundle install -j $(nproc) --deployment
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.velalu.qa

stages:
  - build
  - test
  - publish_docs
  - cleanup
  - publish_image

build:
  stage: build
  script: docker-compose build test

test:
  stage: test
  script: docker-compose run test bundle exec rake db:setup ci

cleanup:
  stage: cleanup
  when: always
  script: docker-compose down

publish_docs:
  stage: publish_docs
  script:
    - script/build_manual
    - bundle exec gitdeploy

publish_image:
  stage: publish_docs
  script:
    - docker tag ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF} ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF_SLUG}
    - docker tag ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF} ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest
    - docker push ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF_SLUG}
    - docker push ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest
