image: registry.vela/velaluqa/gitlab-ci-build-images:ruby-2.3.4-docker

variables:
  BUNDLE_GEMFILE: Gemfile-ci
  REGISTRY: registry.velalu.qa

cache:
  key: 'ruby234'
  paths:
    - vendor/bundle

before_script:
  - bundle install -j $(nproc) --deployment
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.velalu.qa

stages:
  - deploy

run:
  stage: deploy
  script:
    - docker build -t ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF} .
    - docker run --name ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_postgres_${CI_BUILD_ID} -d postgres:9.5
    - docker run --name ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_redis_${CI_BUILD_ID} -d redis
    - echo "Waiting for postgres and redis to start up ..." && sleep 15
    - docker run -t --name ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_test_${CI_BUILD_ID} --link ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_redis_${CI_BUILD_ID}:redis --link ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_postgres_${CI_BUILD_ID}:postgres -e RAILS_ENV=test ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF} sh -c 'rm -f config/database.yml && ln -s database.yml.dev config/database.yml && rake db:setup && COVERAGE=true bundle exec spring rspec --require spec_helper -f html -o reports/unit.html -f JUnit -o reports/rspec_report.xml'
    - docker cp ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_test_${CI_BUILD_ID}:/app/reports .
    - docker rm -f -v ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_test_${CI_BUILD_ID} ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_postgres_${CI_BUILD_ID} ${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_redis_${CI_BUILD_ID}
    - script/build_manual
    - docker tag ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF} ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF_SLUG}
    - docker push ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF_SLUG}
    - bundle exec gitdeploy
