Style/Alias:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/IndentHeredoc:
  EnforcedStyle: active_support

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
