version: "3"

services:
  postgres:
    image: postgres:9.6
  redis:
    image: redis:3.2
  test:
    build: .
    image: ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF}
    command: 'rake setup:db ci'
    environment:
      RAILS_ENV: test
    links:
      - postgres
      - redis
