postgres:
  restart: always
  container_name: erica_postgres_production
  image: postgres
  ports:
    - 5432:5432
  environment:
    POSTGRES_PASSWORD: 'prodtest'
redis:
  restart: always
  container_name: erica_redis_production
  image: redis
  ports:
    - 6379:6379
app:
  build: &build .
  restart: always
  container_name: erica_app_production
  command: bundle exec puma -t 8:16 -w 2 --preload -p 3000
  environment: &environment
    RAILS_ENV: production
    ERICA_HOST: 'localhost:3000'
    POSTGRES_HOST: 'postgres'
    POSTGRES_DATABASE: 'erica_store_development'
    POSTGRES_USERNAME: postgres
    POSTGRES_PASSWORD: prodtest
    SMTP_PORT: 587
    SMTP_SERVER: 'mail.velalu.qa'
    SMTP_USERNAME: pharmtrace@velalu.qa
    SMTP_PASSWORD: password
    SMTP_SENDER: pharmtrace@velalu.qa
    SMTP_STARTTLS_AUTO: 'true'
  ports:
    - 3000
  volumes: &volumes
    - ./data:/app/data
    - ./log:/app/log
    - ./tmp:/app/tmp
  links: &links
    - postgres
    - redis
    - worker
worker:
  restart: always
  container_name: erica_sidekiq_production
  build: .
  command: bundle exec sidekiq -q default -q notifications
  environment: *environment
  volumes: *volumes
  links:
    - postgres
    - redis
https:
  restart: always
  container_name: erica_https_production
  image: nginx
  ports:
    - 443:443
    - 80:80
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx_erica.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - app:rw
  links:
    - app
