version: "3.8"

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=testenv
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
  redis:
    image: redis:3.2
  test:
    build:
      context: .
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      cache_from:
        - ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-cache
        - ${CI_REGISTRY_IMAGE}:develop-cache
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    command: 'rake setup:db ci'
    environment:
      RAILS_ENV: test
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: testenv
      KNAPSACK_TEST_FILE_PATTERN: "spec/**{,/*/**}/{*_spec.rb,*.feature}"
      CI_NODE_TOTAL: ${CI_NODE_TOTAL}
      CI_NODE_INDEX: ${CI_NODE_INDEX}
    privileged: true
    volumes:
      - ${DOCKER_PWD:-.}/reports:/app/reports # Artifacts
      - ${DOCKER_PWD:-.}/.git:/app/.git:ro    # Validation Report requires access to git history
      - ${DOCKER_PWD:-.}/tmp/capybara:/app/tmp/capybara
      - ${DOCKER_PWD:-.}/tmp/downloads:/downloads
    links:
      - postgres
      - redis
      - chrome
      - mailcatcher-test
  mailcatcher-test:
    image: schickling/mailcatcher
    ports:
      - 1080
  chrome:
    image: selenium/standalone-chrome:108.0-chromedriver-108.0-grid-4.7.0-20221202
    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      SE_NODE_SESSION_TIMEOUT: 11000
    shm_size: 2GB
    volumes:
      - ${DOCKER_PWD:-.}/tmp/downloads:/downloads
