mongo:
  image: mongo
postgres:
  image: postgres
redis:
  image: redis
dev:
  build: .
  command: zeus start
  volumes:
    - .:/app
    - ./config/database.yml.dev:/app/config/database.yml
    - ./config/mongoid.yml.dev:/app/config/mongoid.yml
    - ./config/erica_remotes.yml.dev:/app/config/erica_remotes.yml
  ports:
    - 3000:3000
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
  links:
    - postgres
    - mongo
    - redis
