postgres:
  image: postgres:9.5
  ports:
    - 5432:5432
  volumes:
    - ./tmp/postgresql_data_3_0_0:/var/lib/postgresql/data
    - /home/arthur/erp:/dump:ro
mongo:
  image: mongo:3.2
  ports:
    - 27017:27017
  volumes:
    - ./tmp/mongo_data_3_0_0:/data
    - /home/arthur/erp:/dump:ro
redis:
  image: redis
  ports:
    - 6379:6379
app:
  build: &build .
  command: rails s -b 0.0.0.0 -p 3000
  tty: true
  volumes: &volumes
    - .:/app
    - ./config/database.yml.dev:/app/config/database.yml
    - ./config/erica_remotes.yml.dev:/app/config/erica_remotes.yml
    - ./tmp:/app/tmp
  ports:
    - 3000:3000
  environment: &environment
    DB_USERNAME: postgres
    DB_PASSWORD:
    TRUSTED_IP: 172.18.0.1
  links: &links
    - postgres
    - mongo
    - redis
    # - worker
test:
  build: *build
  command: guard
  tty: true
  volumes: *volumes
  environment:
    <<: *environment
    RAILS_ENV: test
  links:
    - postgres
    - redis
worker:
  build: *build
  command: bundle exec sidekiq
  volumes: *volumes
  environment: *environment
  links:
    - postgres
    - redis
https:
  image: nginx
  ports:
    - 443:443
    - 80:80
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./erica.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - app:rw
  links:
    - app
