version: "3"

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=testenv
  redis:
    image: redis:3.2
  test:
    build:
      context: .
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    command: 'rake setup:db ci'
    environment:
      RAILS_ENV: test
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: testenv
    privileged: true
    volumes:
      - ${DOCKER_PWD:-.}/reports:/app/reports # Artifacts
      - ${DOCKER_PWD:-.}/.git:/app/.git:ro    # Validation Report requires access to git history
    links:
      - postgres
      - redis
      - chrome
      - mailcatcher-test
  mailcatcher-test:
    image: schickling/mailcatcher
    ports:
      - 1080
  chrome:
    image: selenium/standalone-chrome
    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
    shm_size: 2GB
