mongo:
  image: mongo
  ports:
    - 27017
db:
  image: postgres
  ports:
    - 5432
redis:
  image: redis
  ports:
    - 6379
app:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - 3000:3000
  environment:
    - RAILS_ENV=production
    - DB_USERNAME=postgres
    - DB_PASSWORD=
  links:
    - db
    - mongo
