mongo:
  image: mongo
postgres:
  image: postgres
redis:
  image: redis
dev:
  build: .
  command: zeus start
  volumes:
    - /zfs/docker/volumes/jenkins-${HOSTNAME}-workspace/pharmtrace-erica-store/reports:/app/reports
    - /zfs/docker/volumes/jenkins-${HOSTNAME}-workspace/pharmtrace-erica-store/config/database.yml.dev:/app/config/database.yml
    - /zfs/docker/volumes/jenkins-${HOSTNAME}-workspace/pharmtrace-erica-store/config/mongoid.yml.dev:/app/config/mongoid.yml
    - /zfs/docker/volumes/jenkins-${HOSTNAME}-workspace/pharmtrace-erica-store/config/erica_remotes.yml.dev:/app/config/erica_remotes.yml
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
  links:
    - postgres
    - mongo
    - redis
