postgres:
  restart: always
  container_name: erica_postgres_production
  image: postgres
  ports:
    - 5432:5432
redis:
  restart: always
  container_name: erica_redis_production
  image: redis
  ports:
    - 6379:6379
app:
  restart: always
  container_name: erica_app_production
  image: &app_image erica:latest
  command: bundle exec unicorn -p 3000
  environment: &environment
    RAILS_ENV: production
  ports:
    - 3000
  volumes: &volumes
    - ./config/database.yml:/app/config/database.yml
    - ./data:/app/data
    - ./log:/app/log
    - ./tmp:/app/tmp
  links: &links
    - postgres
    - redis
worker:
  restart: always
  container_name: erica_sidekiq_production
  image: *app_image
  command: bundle exec sidekiq
  environment: *environment
  volumes: *volumes
  links: *links
https:
  restart: always
  container_name: erica_https_production
  image: nginx
  ports:
    - 443:443
    - 80:80
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx_erica.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - app:rw
  links:
    - app
