postgres:
  container_name: erica_postgres
  image: postgres
  ports:
    - 5432:5432
redis:
  container_name: erica_redis
  image: redis
  ports:
    - 6379:6379
app:
  container_name: erica
  build: .
  command: bundle exec unicorn -p 80
  environment:
    RAILS_ENV: production
  ports:
    - 80:80
  volumes:
    - ./config/database.yml:/app/config/database.yml
    - ./data:/app/data
    - ./log:/app/log
    - ./tmp:/app/tmp
  links:
    - postgres
    - redis
