postgres:
  container_name: erica_postgres
  image: postgres
  ports:
    - 5432:5432
redis:
  container_name: erica_redis
  image: redis
  ports:
    - 6379:6379
app:
  container_name: erica
  image: erica:latest
  command: bundle exec unicorn -p 3000
  environment:
    RAILS_ENV: production
  ports:
    - 3000
  volumes:
    - ./config/database.yml:/app/config/database.yml
    - ./data:/app/data
    - ./log:/app/log
    - ./tmp:/app/tmp
  links:
    - postgres
    - redis
https:
  container_name: erica_https_production
  image: nginx
  ports:
    - 443:443
    - 80:80
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./erica.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - app:rw
  links:
    - app
