version: "2.1"
services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgresql_data_3_0_0/9.6/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD:password
  redis:
    image: redis
    ports:
      - 6379:6379
  mailcatcher-dev:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  mailcatcher-test:
    image: schickling/mailcatcher
    ports:
      - 1080
  app:
    build: &build .
    command: rails s -b 0.0.0.0 -p 3000
    tty: true
    volumes: &volumes
      - .:/app
      - ./config/erica_remotes.yml.dev:/app/config/erica_remotes.yml
      - ./tmp:/app/tmp
      - ./tmp/downloads:/downloads
    ports:
      - 3000:3000
    environment: &environment
      RAILS_ENV: development
      TRUSTED_IP: 172.18.0.1
      DISABLE_SPRING: 't'
      POSTGRES_HOST: postgres
      # POSTGRES_DATABASE: erica_store_production
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    links: &links
      - postgres
      - redis
      - worker
      - webpack
      - mailcatcher-dev
  webpack:
    container_name: erica_webpack
    build: *build
    environment:
      <<: *environment
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: ./bin/webpack-dev-server --no-inline
    entrypoint: ""
    volumes: *volumes
    ports:
      - '3035:3035'
  test:
    build: *build
    command: guard
    tty: true
    volumes: *volumes
    environment:
      <<: *environment
      RAILS_ENV: test
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    links:
      - postgres
      - redis
      - chrome
      - mailcatcher-test
  worker:
    build: *build
    command: bundle exec sidekiq
    volumes: *volumes
    environment: *environment
    links:
      - postgres
      - redis
  https:
    image: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx_erica.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app:rw
    links:
      - app
  chrome:
    #image: selenium/standalone-chrome-debug
    image: selenium/standalone-chrome:108.0-chromedriver-108.0-grid-4.7.0-20221202
    ports:
      - 5900:5900
    shm_size: '512mb'
    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
    shm_size: 512m
    volumes:
      - ./spec/files:/app/spec/files
      - ./tmp/downloads:/downloads
