version: "3"

services:
  postgres:
    image: postgres:9.6
  redis:
    image: redis:3.2
  test:
    build: .
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    command: 'rake setup:db ci'
    environment:
      RAILS_ENV: test
    volumes:
      - ${DOCKER_PWD:-.}/reports:/app/reports
    links:
      - postgres
      - redis
