development:
  migration_db:
    adapter: sqlite
    database: db/migration_mapping_development.sqlite3
  goodimage_db:
    adapter: mysql
    database: goodimage
    username: root
  goodimage_image_storage: "/home/profmaad/Workspace/freelance/PharmTrace/GoodImage Migration/goodimage_image_storage"
    