#!/bin/sh

set -ex

if [ -z $CI ]; then
    docker build -t emacs-docs ./doc
    docker run --rm -v "`pwd`/doc:/workspace" emacs-docs
    rm doc/htmls.tgz
else
    IMAGE=${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_emacs-docs:${CI_BUILD_REF}
    docker build -t ${IMAGE} ./doc

    CONTAINER_NAME=${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_emacs-docs_${CI_BUILD_ID}
    docker create --name ${CONTAINER_NAME} ${IMAGE}

    find doc/ -name \*.org -exec docker cp {} ${CONTAINER_NAME}:/workspace \;
    docker cp doc/elisp ${CONTAINER_NAME}:/workspace
    docker start -a ${CONTAINER_NAME}

    docker cp ${CONTAINER_NAME}:/workspace/htmls.tgz /tmp
    tar xzf /tmp/htmls.tgz -C doc
    rm /tmp/htmls.tgz
    docker rm -v ${CONTAINER_NAME}
    docker rmi --no-prune ${IMAGE}
fi

mkdir -p ./reports/manual
mv -f ./doc/*.html ./reports/manual/
cp -rf ./doc/css ./doc/fonts ./doc/images ./doc/js ./reports/manual/
